use bibliotecapessoal;

ALTER TABLE usuario 
DROP COLUMN dta_cadastro,
ADD COLUMN senha VARCHAR(255) NOT NULL,
ADD COLUMN data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;